from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator
from airflow.operators.python_operator import PythonOperator
from airflow.operators.email_operator import EmailOperator
from datetime import timedelta, datetime
from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator

default_args={
        'owner':'beula',
        'start_date':datetime(2023,7,3),
        'retries':3,
        'retry_delay':timedelta(minutes=5)
        }

dag= DAG('timber_land_stock_analysis',
          default_args=default_args,
          description='airflow project',
          schedule_interval='* * * * *',
          catchup=False,
          tags=['example,helloworld']
          )

start_task = DummyOperator(task_id='start_task',dag=dag)



# Define the Spark job
spark_job = SparkSubmitOperator(
    task_id='spark_job',
    application='/root/airflow/pro_spark.py',
    conn_id='spark_default',
    verbose=1,
    dag=dag
)


end_task = DummyOperator(task_id='end_task',dag=dag)

email_task = EmailOperator(
        task_id='email_task',
        to=['dheena.abc@gmail.com'],
        subject="Spark job ran successfully",
        html_content="<b>output generated by spark in airflow</b>",
        dag=dag
)


start_task >> spark_job >> end_task >> email_task